language: python
python:
  - "3.5"
  - "3.6"
#  - "3.7-dev"  Currently running 3.7 on Ubuntu

install:
  - "curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python"
  - "poetry install"

script:
  - "pytest"
